import type { Locale } from "../i18n.ts";

const RU = {
  sectionTitle: "Групповые звонки",
  sectionLead: "Аудио- и видеоконференции с устойчивым переподключением",
  activeTitle: "Идут сейчас",
  startTitle: "Начать в группе",
  noActive: "Сейчас нет активных групповых звонков.",
  noGroups: "Создайте группу или канал, чтобы начать конференцию.",
  disabled: "Групповые звонки пока не включены на этом сервере.",
  groupKind: "Группа",
  channelKind: "Канал",
  join: "Войти",
  startAudio: "Аудио",
  startVideo: "Видео",
  participants: "Участников: {count}",
  modeConversation: "Свободный разговор",
  modeStage: "Сцена",
  modeBroadcast: "Трансляция",
  loading: "Проверяем активные конференции…",
  retry: "Повторить",
  unavailable: "Не удалось загрузить групповые звонки.",
  connecting: "Подключение…",
  reconnecting: "Восстанавливаем связь…",
  callTitle: "Групповой звонок",
  participantList: "Участники",
  microphoneOn: "Выключить микрофон",
  microphoneOff: "Включить микрофон",
  cameraOn: "Выключить камеру",
  cameraOff: "Включить камеру",
  screenStart: "Показать экран",
  screenStop: "Остановить показ",
  raiseHand: "Поднять руку",
  leave: "Выйти",
  end: "Завершить для всех",
  promote: "Разрешить говорить",
  demote: "Перевести в слушатели",
  remove: "Удалить из звонка",
  pin: "Закрепить видео",
  unpin: "Открепить видео",
  audioBlocked: "Нажмите, чтобы включить звук конференции",
  audioResume: "Включить звук",
  screenDenied: "Доступ к демонстрации экрана не предоставлен.",
  screenUnavailable: "Демонстрация экрана недоступна на этом устройстве.",
  screenFailed: "Не удалось начать демонстрацию экрана.",
  qualityCritical: "Канал слабый: видео приостановлено, голос сохранён.",
  removed: "Вас удалили из конференции.",
  ended: "Конференция завершена.",
  failed: "Соединение с конференцией потеряно.",
  close: "Закрыть",
} as const;

type Dictionary = { [K in keyof typeof RU]: string };

const EN: Dictionary = {
  sectionTitle: "Group calls",
  sectionLead: "Audio and video conferences with resilient reconnection",
  activeTitle: "Live now",
  startTitle: "Start in a group",
  noActive: "There are no active group calls.",
  noGroups: "Create a group or channel to start a conference.",
  disabled: "Group calls are not enabled on this server yet.",
  groupKind: "Group",
  channelKind: "Channel",
  join: "Join",
  startAudio: "Audio",
  startVideo: "Video",
  participants: "Participants: {count}",
  modeConversation: "Open conversation",
  modeStage: "Stage",
  modeBroadcast: "Broadcast",
  loading: "Checking active conferences…",
  retry: "Retry",
  unavailable: "Group calls could not be loaded.",
  connecting: "Connecting…",
  reconnecting: "Restoring the connection…",
  callTitle: "Group call",
  participantList: "Participants",
  microphoneOn: "Mute microphone",
  microphoneOff: "Unmute microphone",
  cameraOn: "Turn camera off",
  cameraOff: "Turn camera on",
  screenStart: "Share screen",
  screenStop: "Stop sharing",
  raiseHand: "Raise hand",
  leave: "Leave",
  end: "End for everyone",
  promote: "Allow to speak",
  demote: "Move to listeners",
  remove: "Remove from call",
  pin: "Pin video",
  unpin: "Unpin video",
  audioBlocked: "Tap to enable conference audio",
  audioResume: "Enable audio",
  screenDenied: "Screen-share permission was not granted.",
  screenUnavailable: "Screen sharing is unavailable on this device.",
  screenFailed: "Screen sharing could not be started.",
  qualityCritical: "Weak connection: video paused, voice kept online.",
  removed: "You were removed from the conference.",
  ended: "The conference has ended.",
  failed: "The conference connection was lost.",
  close: "Close",
};

export type ConferenceTextKey = keyof typeof RU;

export function conferenceText(locale: Locale, key: ConferenceTextKey, vars: Record<string, string> = {}): string {
  let value: string = (locale === "ru" ? RU : EN)[key];
  for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
}
