import type { Locale } from "../i18n.ts";
import type { MiniAppScope } from "./miniapps_model.ts";

const RU = {
  title: "Мини-приложения",
  subtitle: "Сервисы внутри GreenChat без установки и внешних аккаунтов",
  catalog: "Каталог",
  myApps: "Мои приложения",
  open: "Открыть",
  create: "Создать приложение",
  saveDraft: "Сохранить черновик",
  publish: "Опубликовать",
  disable: "Отключить",
  emptyCatalog: "Опубликованных мини-приложений пока нет.",
  emptyMine: "Привяжите первое мини-приложение к своему GreenChat-боту.",
  bot: "Бот",
  titleField: "Название",
  description: "Описание",
  launchUrl: "HTTPS-адрес приложения",
  scopes: "Разрешения",
  draft: "Черновик",
  active: "Опубликовано",
  disabled: "Отключено",
  saved: "Черновик сохранён. После изменения адреса или разрешений приложение нужно опубликовать заново.",
  published: "Приложение опубликовано.",
  disabledDone: "Приложение отключено, активные запуски и разрешения отозваны.",
  loading: "Загрузка…",
  retry: "Повторить",
  back: "Назад",
  settings: "Настройки",
  mainAction: "Основное действие",
  consentTitle: "Разрешить запуск?",
  consentLead: "Мини-приложение получит только перечисленные данные. Разрешение можно отозвать позже.",
  allowOpen: "Разрешить и открыть",
  cancel: "Отмена",
  revoked: "Отозвать доступ",
  close: "Закрыть",
  unavailable: "Мини-приложение недоступно или отключено.",
  invalidOrigin: "Адрес приложения не совпадает с опубликованным доменом.",
  frameError: "Не удалось загрузить мини-приложение.",
  clipboardDenied: "Приложение не получило разрешение на запись в буфер обмена.",
  copied: "Скопировано.",
  invoiceTitle: "Подтверждение оплаты",
  invoiceRecipient: "Получатель",
  invoiceAmount: "Сумма",
  invoiceDescription: "Назначение",
  invoiceExpires: "Счёт действует до",
  invoicePay: "Оплатить",
  invoiceCancel: "Отмена",
  invoicePin: "Платёжный PIN",
  invoicePinHint: "PIN вводится только в системном окне GreenChat",
  invoiceLoading: "Проверяем счёт…",
  invoicePaid: "Счёт оплачен.",
  invoiceUnavailable: "Счёт недоступен, закрыт или принадлежит другому боту.",
  invoiceScopeDenied: "Приложение не получило разрешение на оплату счетов.",
  analytics: "Аналитика",
  analyticsPeriod: "Последние 30 дней",
  analyticsLaunches: "Запуски",
  analyticsChatLaunches: "Из чатов",
  analyticsGrants: "Новые согласия",
  analyticsVerifications: "Проверки backend",
  analyticsTrend: "Последние 7 дней",
  analyticsPrivacy: "Только агрегаты: без пользователей, чатов и содержимого.",
  analyticsUnavailable: "Не удалось проверить аналитику приложения.",
  scopeUser: "Основной профиль: ID, имя, username и аватар",
  scopeTheme: "Тема и цвета интерфейса GreenChat",
  scopeChat: "Контекст текущего чата, только при запуске из чата",
  scopeClipboard: "Запись текста в буфер обмена по команде приложения",
  scopeInvoice: "Запрос системной оплаты счёта этого бота; PIN и подтверждение остаются в GreenChat",
} as const;

type MiniAppsDictionary = { [K in keyof typeof RU]: string };

const EN: MiniAppsDictionary = {
  title: "Mini Apps",
  subtitle: "Services inside GreenChat without installation or external accounts",
  catalog: "Catalog",
  myApps: "My apps",
  open: "Open",
  create: "Create app",
  saveDraft: "Save draft",
  publish: "Publish",
  disable: "Disable",
  emptyCatalog: "There are no published Mini Apps yet.",
  emptyMine: "Attach your first Mini App to a GreenChat bot.",
  bot: "Bot",
  titleField: "Title",
  description: "Description",
  launchUrl: "Application HTTPS URL",
  scopes: "Permissions",
  draft: "Draft",
  active: "Published",
  disabled: "Disabled",
  saved: "Draft saved. Address or permission changes require publishing again.",
  published: "Application published.",
  disabledDone: "Application disabled; active launches and grants were revoked.",
  loading: "Loading…",
  retry: "Retry",
  back: "Back",
  settings: "Settings",
  mainAction: "Main action",
  consentTitle: "Allow this launch?",
  consentLead: "The Mini App receives only the listed data. You can revoke access later.",
  allowOpen: "Allow and open",
  cancel: "Cancel",
  revoked: "Revoke access",
  close: "Close",
  unavailable: "The Mini App is unavailable or disabled.",
  invalidOrigin: "The application URL does not match its published origin.",
  frameError: "The Mini App could not be loaded.",
  clipboardDenied: "The app has no clipboard-write permission.",
  copied: "Copied.",
  invoiceTitle: "Confirm payment",
  invoiceRecipient: "Recipient",
  invoiceAmount: "Amount",
  invoiceDescription: "Description",
  invoiceExpires: "Invoice expires",
  invoicePay: "Pay",
  invoiceCancel: "Cancel",
  invoicePin: "Payment PIN",
  invoicePinHint: "The PIN is entered only in GreenChat's system sheet",
  invoiceLoading: "Checking invoice…",
  invoicePaid: "Invoice paid.",
  invoiceUnavailable: "The invoice is unavailable, closed, or belongs to another bot.",
  invoiceScopeDenied: "The app has no permission to request invoice payments.",
  analytics: "Analytics",
  analyticsPeriod: "Last 30 days",
  analyticsLaunches: "Launches",
  analyticsChatLaunches: "From chats",
  analyticsGrants: "New consents",
  analyticsVerifications: "Backend verifications",
  analyticsTrend: "Last 7 days",
  analyticsPrivacy: "Aggregates only: no users, chats, or content.",
  analyticsUnavailable: "Could not verify app analytics.",
  scopeUser: "Basic profile: ID, name, username and avatar",
  scopeTheme: "GreenChat theme and interface colors",
  scopeChat: "Current chat context, only when launched from a chat",
  scopeClipboard: "Write text to the clipboard when requested by the app",
  scopeInvoice: "Request a system payment for this bot's invoice; PIN and confirmation stay in GreenChat",
};

export type MiniAppsTextKey = keyof typeof RU;

export function miniAppsText(locale: Locale, key: MiniAppsTextKey): string {
  return (locale === "ru" ? RU : EN)[key];
}

export function miniAppScopeText(locale: Locale, scope: MiniAppScope): string {
  switch (scope) {
    case "user.basic": return miniAppsText(locale, "scopeUser");
    case "theme": return miniAppsText(locale, "scopeTheme");
    case "chat.context": return miniAppsText(locale, "scopeChat");
    case "clipboard.write": return miniAppsText(locale, "scopeClipboard");
    case "payments.invoice": return miniAppsText(locale, "scopeInvoice");
  }
}
