// Regression: the message menu must survive the gesture that opens it.
//
// Long-press mounts the sheet while the finger is still down. On release the browser synthesises a
// click at that same point, which lands on the freshly mounted sheet. Measured in a real touch
// context before the fix: the menu existed during the press and was gone the moment the finger came
// up — the message menu was unreachable on every touch device, and a synthetic click landing on a
// row could have run an action (e.g. delete) that nobody chose.
import test from "node:test";
import assert from "node:assert/strict";

import { createI18n } from "../src/i18n.ts";
import { en } from "../src/locales/en.ts";
import { ru } from "../src/locales/ru.ts";
import { installDomStub, StubNode } from "./dom_stub.ts";

installDomStub();

const { openMessageMenu } = await import("../src/screens/message_menu.ts");
const i18n = createI18n({ locale: "en", dicts: { en, ru } });

interface Opened {
  host: StubNode;
  layer: StubNode;
  item: StubNode;
  reaction: StubNode;
  counters: { ran: number; reacted: number };
}

function openSheet(): Opened {
  const counters = { ran: 0, reacted: 0 };
  const host = new StubNode("div");
  const handle = openMessageMenu({
    i18n,
    host: host as unknown as HTMLElement,
    quickReactions: ["👍"],
    onReact: () => { counters.reacted++; },
    items: [{ id: "delete", label: "Delete", glyph: "trash", run: () => { counters.ran++; } }],
  });
  const layer = handle.root as unknown as StubNode;
  const item = layer.find((n) => n.attrs["data-action"] === "delete")!;
  const reaction = layer.find((n) => n.hasClass("gc-msgmenu-reaction"))!;
  return { host, layer, item, reaction, counters };
}

test("the tail click of the opening long-press neither closes the sheet nor fires an action", () => {
  const s = openSheet();
  assert.equal(s.host.children.includes(s.layer), true, "sheet is mounted");

  // detail >= 1 marks a pointer-derived click; no press has started inside the sheet yet.
  s.item.dispatch("click", { detail: 1 });
  assert.equal(s.counters.ran, 0, "no action may run from the gesture that opened the menu");

  s.reaction.dispatch("click", { detail: 1 });
  assert.equal(s.counters.reacted, 0, "no reaction may be sent either");

  s.layer.dispatch("click", { target: s.layer, detail: 1 });
  assert.equal(s.host.children.includes(s.layer), true, "the sheet stays open");
});

test("a press that starts inside the sheet arms it: items run and the scrim closes", () => {
  const s = openSheet();
  s.layer.dispatch("pointerdown", {});
  s.item.dispatch("click", { detail: 1 });
  assert.equal(s.counters.ran, 1, "a deliberate tap runs the action");
  assert.equal(s.host.children.includes(s.layer), false, "and closes the sheet");

  const t = openSheet();
  t.layer.dispatch("touchstart", {}); // no Pointer Events in the stub → raw touch fallback arms it
  t.layer.dispatch("click", { target: t.layer, detail: 1 });
  assert.equal(t.host.children.includes(t.layer), false, "a deliberate scrim tap closes the sheet");
});

test("keyboard activation is honoured without any preceding press", () => {
  const s = openSheet();
  s.item.dispatch("click", { detail: 0 }); // click generated by Enter/Space on a focused menu item
  assert.equal(s.counters.ran, 1);
  assert.equal(s.host.children.includes(s.layer), false);
});

test("the compatibility mouse events Chrome replays after a touch do not arm the sheet", () => {
  // Chrome replays mousedown/mouseup/click at the release point of a touch. That replay lands on the
  // sheet the long-press just mounted there, so it must never count as a deliberate press. Where
  // Pointer Events exist (every engine the client ships to), only pointerdown arms the menu.
  const g = globalThis as { PointerEvent?: unknown };
  const had = "PointerEvent" in g;
  g.PointerEvent = class {};
  try {
    const s = openSheet();
    s.layer.dispatch("mousedown", {});
    s.item.dispatch("click", { detail: 1 });
    assert.equal(s.counters.ran, 0, "a replayed compatibility click must not run an action");
    assert.equal(s.host.children.includes(s.layer), true, "and must not close the sheet");

    s.layer.dispatch("pointerdown", {});
    s.item.dispatch("click", { detail: 1 });
    assert.equal(s.counters.ran, 1, "a real press still works");
  } finally {
    if (!had) delete g.PointerEvent;
  }
});

test("the sheet is modal: everything behind it goes inert while open and is restored on close", () => {
  // Dimming the background is paint only. Before this, Tab still walked into the greyed-out
  // conversation behind the sheet, assistive technology still announced it, and the pixel audit
  // measured text under the scrim at 1.38:1 — because that text was still exposed content.
  const counters = { ran: 0 };
  const host = new StubNode("div");
  const behind = new StubNode("div");
  host.append(behind);

  const handle = openMessageMenu({
    i18n,
    host: host as unknown as HTMLElement,
    items: [{ id: "delete", label: "Delete", glyph: "trash", run: () => { counters.ran++; } }],
  });

  assert.equal(behind.attrs.inert, "", "the conversation behind the sheet is inert while it is open");
  const layer = handle.root as unknown as StubNode;
  assert.equal(layer.attrs.inert, undefined, "the sheet itself must stay interactive");

  handle.close();
  assert.equal(behind.attrs.inert, undefined, "closing the sheet gives the background back");
});
