// SPDX-License-Identifier: AGPL-3.0-or-later
const ru = {
  offline: "Нет сети. Последние данные доступны только для просмотра. Уже отправленное действие могло выполниться; после восстановления связи проверим статус, но не будем повторять действие.",
  hexColor: "Код цвета", invalidColor: "Введите # и шесть символов: 0–9, A–F.",
  effectsPaused: "Демонстрация отключена: включено уменьшение движения.",
  effectsContrast: "Демонстрация отключена в режиме высокой контрастности. Выбранный цвет не сбрасывается.",
  incompatibleSettings: "Настройки записаны другой версией приложения и не будут перезаписаны. Этот выбор действует до закрытия приложения.",
  disconnectQuestion: "Отключить аккаунт", cancelWaiting: "Прервать ожидание",
  cancelled: "Ожидание прервано. Уже принятое сервером действие могло выполниться — обновите статус.",
  staleStatus: "Статус требует повторной проверки", statusConfirmed: "Статус подтверждён сервером.",
  unlinkPending: "Отключаем аккаунт…", visibilityPending: "Сохраняем видимость…",
  pageProgress: "Страница {current} из {total}",
  hub: "Эффекты и подключения", hubHint: "Волна нажатия, анимации и привязки аккаунтов",
  settings: "Пусть интерфейс откликается", settingsHint: "Ваши настройки на этом устройстве. Работают и вне игрового режима.",
  close: "Закрыть", back: "Назад", next: "Далее", done: "Готово", later: "Позже",
  wave: "Волна нажатия", waveHint: "Мягкий круг в точке касания — на кнопках и на свободном месте.",
  color: "Цвет волны", customColor: "Свой цвет", reduced: "Уменьшить движение",
  reducedHint: "Без декоративных волн и перемещений. Системная настройка также учитывается.",
  systemReduced: "В системе включено уменьшение движения: декоративные эффекты отключены.",
  demo: "Нажмите здесь", demoHint: "Попробуйте эффект, не включая его во всём приложении.",
  saved: "Настройки сохранены на этом устройстве.", notSaved: "Хранилище недоступно. Настройка действует до закрытия приложения.",
  preview: "Посмотреть возможности", connections: "Подключения", connectionsHint: "Epic Games остаётся в игровом профиле. TikTok доступен только в социальной ленте.",
  authNote: "Вход выполняется у самого сервиса. GreenChat не просит пароль от TikTok или Epic Games.",
  available: "Можно подключить", unavailable: "Подключение ещё не настроено на сервере", linked: "Аккаунт подтверждён",
  connect: "Подключить", disconnect: "Отключить", confirmDisconnect: "Подтвердить отключение", cancel: "Отмена",
  visibility: "Показывать подключённый аккаунт", refresh: "Обновить статус", loading: "Проверяем подключения…",
  pending: "Завершите действие в окне сервиса…", loadError: "Не удалось получить статус. Последние данные могут быть устаревшими.",
  actionError: "Не удалось подтвердить результат. Обновите статус перед повторной попыткой.", timeout: "Время ожидания истекло. Проверьте статус и повторите попытку.",
  unconfirmed: "Сервер пока не подтвердил изменение. Обновите статус подключения.",
  newLabel: "Возможности GreenChat", title: "Новые связи. Живой интерфейс.", subtitle: "Больше индивидуальности — без лишнего шума.",
  overviewTab: "Обзор", waveTab: "Волна", linksTab: "Связи",
  previewWaveTitle: "Одно касание — мягкая волна", previewWaveHint: "Выбранный цвет сохраняется для всего приложения. Попробуйте волну здесь; включить её везде можно в общих настройках.",
  previewLinksTitle: "Ваши аккаунты рядом", previewLinksHint: "Для подтверждённой привязки требуется настроенная серверная интеграция. Введённый ник не считается подтверждением.",
  configure: "Настроить эффекты", openConnections: "Открыть подключения",
  smooth: "Спокойное движение", smoothHint: "Плавное появление карточек и переходы без скачков. Эффекты можно уменьшить.",
  providersHint: "TikTok — только социальная лента. Epic Games — игровая интеграция.",
  colorGreen: "Зелёный", colorBlue: "Голубой", colorViolet: "Сиреневый", colorPink: "Розовый", colorAmber: "Янтарный",
};
const en: Record<keyof typeof ru, string> = {
  offline: "Offline. Last known data is read-only. A request already sent may have completed. When connectivity returns, we will check status without replaying the action.",
  hexColor: "Color code", invalidColor: "Enter # followed by six characters: 0–9, A–F.",
  effectsPaused: "Preview is paused because reduced motion is enabled.",
  effectsContrast: "Preview is paused in high-contrast mode. Your selected color is not reset.",
  incompatibleSettings: "Another app version wrote these settings, so they will not be overwritten. This choice lasts until the app closes.",
  disconnectQuestion: "Disconnect account from", cancelWaiting: "Stop waiting",
  cancelled: "Waiting stopped. A request already accepted by the server may still complete. Refresh status.",
  staleStatus: "Status needs to be checked again", statusConfirmed: "Status confirmed by the server.",
  unlinkPending: "Disconnecting account…", visibilityPending: "Saving visibility…",
  pageProgress: "Page {current} of {total}",
  hub: "Effects and connections", hubHint: "Tap ripples, motion and linked accounts",
  settings: "An interface that responds", settingsHint: "Preferences for this device. Also available outside gaming mode.",
  close: "Close", back: "Back", next: "Next", done: "Done", later: "Later",
  wave: "Tap ripple", waveHint: "A soft circle at your touch, on controls and empty space alike.",
  color: "Ripple color", customColor: "Custom color", reduced: "Reduce motion",
  reducedHint: "No decorative ripples or movement. Your system preference is also respected.",
  systemReduced: "Your system requests reduced motion. Decorative effects are disabled.",
  demo: "Tap here", demoHint: "Try the ripple without enabling it throughout the app.",
  saved: "Preferences saved on this device.", notSaved: "Storage is unavailable. This preference lasts until the app closes.",
  preview: "Explore features", connections: "Connections", connectionsHint: "Epic Games stays in the gaming profile. TikTok is available only in the social feed.",
  authNote: "Sign in with the service itself. GreenChat never asks for your TikTok or Epic Games password.",
  available: "Ready to connect", unavailable: "Server integration is not configured yet", linked: "Account verified",
  connect: "Connect", disconnect: "Disconnect", confirmDisconnect: "Confirm disconnect", cancel: "Cancel",
  visibility: "Show linked account", refresh: "Refresh status", loading: "Checking connections…",
  pending: "Complete the action in the service window…", loadError: "Could not load status. Previously confirmed data may be outdated.",
  actionError: "Could not confirm the result. Refresh status before trying again.", timeout: "The request timed out. Check status and try again.",
  unconfirmed: "The server has not confirmed the change yet. Refresh the connection status.",
  newLabel: "GreenChat features", title: "New connections. A living interface.", subtitle: "More personality. Less distraction.",
  overviewTab: "Overview", waveTab: "Ripple", linksTab: "Connections",
  previewWaveTitle: "One tap. A gentle ripple.", previewWaveHint: "Your chosen color is saved for the whole app. Try the ripple here; enable it everywhere in general settings.",
  previewLinksTitle: "Your accounts, together", previewLinksHint: "Verified linking requires a configured server integration. A typed nickname is not verification.",
  configure: "Customize effects", openConnections: "Open connections",
  smooth: "Considered motion", smoothHint: "Soft card entrances and transitions without jumping. Motion can be reduced.",
  providersHint: "TikTok is social-feed only. Epic Games remains a gaming integration.",
  colorGreen: "Green", colorBlue: "Blue", colorViolet: "Violet", colorPink: "Pink", colorAmber: "Amber",
};
export type EffectCopy = Record<keyof typeof ru, string>;
export const effectCopy = (locale: string): EffectCopy => locale.toLowerCase().startsWith("ru") ? ru : en;
